### ISSUE TITLE
How to divide the suite files dynamically

### ISSUE THREAD

**Issue by Prabakar89** [akash0x53/robot-parallel#1]
We have a requirement to adapt the same script for parallel execution but we need to split it dynamically.
Is there a way to do it ?

Else if the files are out of range we need to abort the execution instead of executing all files again.
Now if we have only 3 suite files and if we use SplitSuite.py:5:4 we are getting this error and all three files are executed. 
suite_to_execute = chunked_suites[self.which_part-1]

**Comment by akash0x53** [comment]
No this is wrong, `SplitSuite.py:5:4` this will try to divide all test suite into 5 parts and run 4th part from that group.

**Comment by Prabakar89** [comment]
Thanks for the clarification
